apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: etcd
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/etcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kcp-system
  timeout: 2m
