apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kcp-demo-controller
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/kcp-demo-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kcp-system
